name: Generate a Flutter application template

on: [push]

permissions:
  contents: write

# if condition must be changed to github.repository != 'Reboot-System-Inc/flutter_riverpod_ddd_template'

jobs:
  create-project:
    if: ${{ github.repository	!= 'Reboot-System-Inc/flutter_riverpod_ddd_template' }}
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
        with:
          # by default, it uses a depth of 1
          # this fetches all history so that we can read each commit
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          
      - run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}' | tr '-' '_' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        shell: bash

      - run: echo "REPOSITORY_URLNAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash

      - run: echo "REPOSITORY_OWNER=$(echo '${{ github.repository }}' | awk -F '/' '{print $1}')" >> $GITHUB_ENV
        shell: bash
      
      - run: |
          email=$(curl \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/users/${{ env.REPOSITORY_OWNER }} \
            | jq -r '.email')

          if [ $email == null ]; then
            echo "REPO_ORGANIZATION=com.${{ env.REPOSITORY_OWNER }} >> $GITHUB_ENV"
            exit 0;
          fi
          
          domain=$(echo $email | rev | cut -d\@ -f1 | rev) 
          secondlevel_domain=$(echo $domain | cut -d. -f1)
          toplevel_domain=$(echo $domain | cut -d. -f2)

          echo "REPO_ORGANIZATION=${toplevel_domain}.${secondlevel_domain}" >> $GITHUB_ENV

      - name: Get Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
  
      - name: Create the project
        run: |
          organization="reboot.${{ env.REPOSITORY_NAME }}"
          repo_name="${{ env.REPOSITORY_NAME }}"

          echo "Creating the project with org ${organization} name ${repo_name}"

          dart pub global activate very_good_cli
          very_good create flutter_app "${repo_name}" --org "$organization"
          cp -r "${repo_name}"/. .
          rm -rf "${repo_name}"

          flutter pub add flutter_easylogger
          flutter pub add hooks_riverpod
          flutter pub add app_version_update
          flutter pub add bot_toast
          flutter pub add cached_network_image
          flutter pub add equatable
          flutter pub add fast_immutable_collections
          flutter pub add flex_color_scheme
          flutter pub add flutter_screenutil
          flutter pub add flutter_svg
          flutter pub add font_awesome_flutter
          flutter pub add form_validator
          flutter pub add fpdart
          flutter pub add google_fonts
          flutter pub add hive_flutter
          flutter pub add hive_flutter
          flutter pub add gap
          flutter pub add go_router
          flutter pub add http
          flutter pub add icons_plus
          flutter pub add image_picker
          flutter pub add intl
          flutter pub add pinput
          flutter pub add timeago
          flutter pub remove very_good_analysis
          

          

      - name: Copy folder base
        run: |
          git clone https://github.com/Reboot-System-Inc/demo temp_repo
          cp -r temp_repo/lib/ .
          rm -rf temp_repo
          

      - name: Self-destruct
        run: |
          rm -rf .github/workflows/

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Ready to clone and code."
          # file_pattern: ':(exclude).github/**'
          push_options: --force
